backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
logo_url: https://totalstopfireperu/img/logo.svg

collections: 
  - name: 'Empresa'
    label: 'empresa'
    delete: false
    editor:
      preview: false
    files:
      - file: 'src/pages/empresa/office-hours.md'
        name: 'office-hours'
        label: 'Horario de oficina'
        description: 'Horario de oficina'
        fields:
          - {label: 'OfficeHours', name: 'widgets', widget: 'hidden', default: 'OfficeHours'}
          - {label: 'Titulo', name: 'titulo', widget: 'string'}
          - {label: 'Lunes', name: 'lunes', widget: 'string'}
          - {label: 'Martes', name: 'martes', widget: 'string'}
          - {label: 'Miércoles', name: 'miercoles', widget: 'string'}
          - {label: 'Jueves', name: 'jueves', widget: 'string'}
          - {label: 'Viernes', name: 'viernes', widget: 'string'}
          - {label: 'Sabado', name: 'sabado', widget: 'string'}
          - {label: 'Domingo', name: 'domingo', widget: 'string'}

      - file: 'src/pages/empresa/contact-info.md'
        name: 'contact-info'
        label: 'Datos de contacto'
        description: 'Datos de contacto'
        fields:
          - {label: 'ContactInfo', name: 'widgets', widget: 'hidden', default: 'ContactInfo'}
          - {label: 'Titulo', name: 'titulo', widget: 'string'}
          - {label: 'Dirección', name: 'direccion', widget: 'string'}
          - {label: 'Teléfono', name: 'telefono', widget: 'string'}
          - {label: 'Móvil', name: 'movil', widget: 'string'}
          - {label: 'Correo electrónico', name: 'correo', widget: 'string'}         

      - file: "src/pages/empresa/social-links.md"
        label: "Redes Sociales"
        name: "social-links"
        description: 'Datos de contacto'
        fields:
          - {label: "SocialLinks", name: "social", widget: "hidden", default: "SocialLinks"}
          - label: "Red Social"
            name: redsocial
            widget: list
            fields:
              - {label: Tipo, name: tipo, widget: select , options: ["Facebook", "Google-Plus", "Youtube","Instagram","Twitter","Skype"]}
              - {label: "Dirreción", name: direccion, widget: string}

  - name: "slider"
    label: "Portada"
    delete: false
    editor:
      preview: false
    files:
      - file: "src/pages/slider/home.md"
        label: "Inicio"
        name: "slider-home"
        fields:
          - {label: "SliderHome", name: "slider", widget: "hidden", default: "SliderHome"}
          - label: Pagina
            name: pagina
            widget: list
            fields:
              - {label: Titulo, name: titulo, widget: string}
              - {label: "Descripción", name: "descripcion", widget: "text"}
              - {label: Imagen, name: imagen, widget: image}              