backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
logo_url: https://totalstopfireperu/img/logo.svg

collections: 
  - label: "Empresa"
    name: "empresa"
    files:
      - label: "Horario de oficina"
        name: "office-hours"
        file: "src/pages/empresa/office-hours.md"
        fields:
          - {label: "OfficeHours", name: "widgets", widget: "hidden", default: "OfficeHours"}
          - {label: "Titulo", name: "titulo", widget: "string"}
          - {label: "Lunes", name: "lunes", widget: "string"}
          - {label: "Martes", name: "martes", widget: "string"}
          - {label: "Miércoles", name: "miercoles", widget: "string"}
          - {label: "Jueves", name: "jueves", widget: "string"}
          - {label: "Viernes", name: "viernes", widget: "string"}
          - {label: "Sabado", name: "sabado", widget: "string"}
          - {label: "Domingo", name: "domingo", widget: "string"}
      - label: "Datos de contacto"
        name: "contact-info"
      - file: "src/pages/empresa/contact-info.md"
        fields:
          - {label: "ContactInfo", name: "widgets", widget: "hidden", default: "ContactInfo"}
          - {label: "Titulo", name: "titulo", widget: "string"}
          - {label: "Dirección", name: "direccion", widget: "string"}
          - {label: "Teléfono", name: "telefono", widget: "string"}
          - {label: "Móvil", name: "movil", widget: "string"}
          - {label: "Correo electrónico", name: "correo", widget: "string"}         
      - label: "Redes Sociales"
        name: "social-links"
        file: "src/pages/empresa/social-links.md"
        fields:
          - {label: "SocialLinks", name: "social", widget: "hidden", default: "SocialLinks"}
          - label: "Red Social"
            name: redsocial
            widget: list
            fields:
              - {label: Tipo, name: tipo, widget: select , options: ["Facebook", "Google-Plus", "Youtube","Instagram","Twitter","Skype"]}
              - {label: "Dirreción", name: direccion, widget: string}         